config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'distance', to: 'pages#distance'
  get 'calculated', to: 'pages#calculated'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def calculated
    point_a = latlong(params[:pointa])
    point_b = latlong(params[:pointb])
    @great_circle = calculate_gc(point_a, point_b)
    @rhumb_dist = calculate_rhumb(point_a, point_b)
  end

  def distance; end

  private

  def latlong(address)
    Geocoder.search(address).first.coordinates
  end

  def calculate_gc(a, b)
    radius = 6371
    d_lat = (b[0] - a[0]) * (Math::PI / 180)
    d_long = (b[1] - a[1]) * (Math::PI / 180)
    first = Math.sin(d_lat / 2) * Math.sin(d_lat / 2) +
            Math.cos((a[0]) * (Math::PI / 180)) *
            Math.cos((b[0]) * (Math::PI / 180)) *
            Math.sin(d_long / 2) * Math.sin(d_long / 2)
    second = 2 * Math.atan2(Math.sqrt(first), Math.sqrt(1 - first))
    radius * second # Distance in km
  end

  def calculate_rhumb(point_a, point_b)
    radius = 6371e3; # metres
    lat_a = point_a[0] * Math::PI / 180
    lat_b = point_b[0] * Math::PI / 180
    d_lat = (point_b[0] - point_a[0]) * Math::PI / 180
    d_long = longitude_diff(point_a[1], point_b[1]) * Math::PI / 180
    dep = Math.log(Math.tan(Math::PI / 4 + lat_b / 2) / Math.tan(Math::PI / 4 + lat_a / 2))
    q = dep.abs > 10e-12 ? d_lat/dep : Math.cos(lat_a) # E-W course becomes ill-conditioned with 0/0

    Math.sqrt(d_lat * d_lat + q * q * d_long * d_long) * radius / 1000 # distance in kilometers
  end

  def mean_latitude(lat_a, lat_b)
    sign_check = (lat_a.positive? && lat_b.positive?) || ((lat_a.negative? && lat_b.negative?))
    if sign_check
      lat_a.positive? ? (lat_a + lat_b) / 2 : -(lat_a + lat_b) / 2
    elsif lat_a.positive?
      (lat_a + lat_b) > 0 ? (lat_a + lat_b) / 2 : (lat_b + lat_a) / 2
    else
      (lat_b - lat_a) > 0 ? (lat_b + lat_a) / 2 : (lat_a + lat_b) / 2
    end
  end

  def longitude_diff(long_a, long_b)
    sign_check = (long_a.positive? && long_b.positive?) || (long_a.negative? && long_b.negative?)
    if sign_check
      long_a > long_b ? long_a - long_b : long_b - long_a
    elsif long_a.positive?
      (long_a - long_b) > 180 ? (180 - long_a) + (180 + long_b) : long_a - long_b
    else
      (long_b - long_a) > 180 ? (180 - long_b) + (180 + long_a) : long_b - long_a
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDistanceCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_calculator.html.erb
<div class="my-3 d-flex justify-content-between px-3">
  <h1 class="title">This is your distance calculator</h1>
  <div class="d-flex align-items-center gap-2 p-2" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    <%= form_with url: calculated_path, method: :get do %>
      <%= text_field_tag :pointa,
        params[:pointa],
        class: "rounded-pill",
        placeholder: "Start point"
      %>
      <%= text_field_tag :pointb,
        params[:pointb],
        class: "rounded-pill",
        placeholder: "Finish point"
      %>
      <%= submit_tag "Calculate", class: "btn btn-dark rounded-pill" %>
    <% end %>
  </div>
</div>

app/views/pages/_results.html.erb
<div class="container d-flex gap-5 my-3 shadow text-bg-secondary rounded">
  <div>
  <p><strong>Straight line distance:</strong> <%= @rhumb_dist.round(3) %> Kilometers</p>
  <p><strong>Great circle distance:</strong> <%= @great_circle.round(3) %> Kilometers</p>
  </div>
  <div class="d-flex align-items-center">
    <p>If you followed a straight line you would travel <strong><%= (@rhumb_dist.round(3) - @great_circle.round(3)).round(3) %></strong> kilometers more</p>
  </div>
</div>
<div class="container">
    <p>** The greater the distance between the places, the more efficient it is to go in a great circle route</p>
</div>

app/views/pages/calculated.html.erb
<%= render 'calculator' %>
<%= render 'results' %>
<embed type="text/html" src="distance.html" width="100%" height="600">

app/views/pages/distance.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Measure distances</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
<link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
<style>
body { margin: 0; padding: 0; }
#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<style>
.distance-container {
position: absolute;
top: 10px;
left: 10px;
z-index: 1;
}

.distance-container > * {
background-color: rgba(0, 0, 0, 0.5);
color: #fff;
font-size: 11px;
line-height: 18px;
display: block;
margin: 0;
padding: 5px 10px;
border-radius: 3px;
}
</style>

<div id="map"></div>
<div id="distance" class="distance-container"></div>

<script src="https://unpkg.com/@turf/turf@6/turf.min.js"></script>
<script>
	mapboxgl.accessToken = 'pk.eyJ1Ijoia3VtbWVyZiIsImEiOiJjbGEyc2I1ZnQwa2xiM3hvMzE1bnI4bnBvIn0.FlMw1nMbJuYXbPOYgA8ySA';
const map = new mapboxgl.Map({
container: 'map',
// Choose from Mapbox's core styles, or make your own style with Mapbox Studio
style: 'mapbox://styles/mapbox/streets-v12',
center: [1, 1],
zoom: 1.4
});

const distanceContainer = document.getElementById('distance');

// GeoJSON object to hold our measurement features
const geojson = {
'type': 'FeatureCollection',
'features': []
};

// Used to draw a line between points
const linestring = {
'type': 'Feature',
'geometry': {
'type': 'LineString',
'coordinates': []
}
};

map.on('load', () => {
map.addSource('geojson', {
'type': 'geojson',
'data': geojson
});

// Add styles to the map
map.addLayer({
id: 'measure-points',
type: 'circle',
source: 'geojson',
paint: {
'circle-radius': 5,
'circle-color': '#000'
},
filter: ['in', '$type', 'Point']
});
map.addLayer({
id: 'measure-lines',
type: 'line',
source: 'geojson',
layout: {
'line-cap': 'round',
'line-join': 'round'
},
paint: {
'line-color': '#000',
'line-width': 2.5
},
filter: ['in', '$type', 'LineString']
});

map.on('click', (e) => {
const features = map.queryRenderedFeatures(e.point, {
layers: ['measure-points']
});

// Remove the linestring from the group
// so we can redraw it based on the points collection.
if (geojson.features.length > 1) geojson.features.pop();

// Clear the distance container to populate it with a new value.
distanceContainer.innerHTML = '';

// If a feature was clicked, remove it from the map.
if (features.length) {
const id = features[0].properties.id;
geojson.features = geojson.features.filter(
(point) => point.properties.id !== id
);
} else {
const point = {
'type': 'Feature',
'geometry': {
'type': 'Point',
'coordinates': [e.lngLat.lng, e.lngLat.lat]
},
'properties': {
'id': String(new Date().getTime())
}
};

geojson.features.push(point);
}

if (geojson.features.length > 1) {
linestring.geometry.coordinates = geojson.features.map(
(point) => point.geometry.coordinates
);

geojson.features.push(linestring);

// Populate the distanceContainer with total distance
const value = document.createElement('pre');
const distance = turf.length(linestring);
value.textContent = `Total distance: ${distance.toLocaleString()}km`;
distanceContainer.appendChild(value);
}

map.getSource('geojson').setData(geojson);
});
});

map.on('mousemove', (e) => {
const features = map.queryRenderedFeatures(e.point, {
layers: ['measure-points']
});
// Change the cursor to a pointer when hovering over a point on the map.
// Otherwise cursor is a crosshair.
map.getCanvas().style.cursor = features.length
? 'pointer'
: 'crosshair';
});
</script>

</body>
</html>

app/views/pages/home.html.erb
<div class="my-3 d-flex justify-content-between px-3">
  <h1 class="title">This is your distance calculator</h1>
  <div class="d-flex align-items-center gap-2 p-2" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    <input type="text" class="rounded-pill" data-address-autocomplete-target="pointb">|
    <input type="text" class="rounded-pill" data-address-autocomplete-target="pointa">
    <button class="btn btn-dark rounded-pill" data-action="click->address-autocomplete#getLatLong">Calculate</button>
  </div>
</div>
<embed type="text/html" src="distance.html" width="100%" height="600">